services:
  discord-bot:
    build: .
    command: poetry run python main.py
    restart: unless-stopped
    networks:
      - discord-bot-tier
    volumes:
      - ./config:/config
    environment:
      DiscordToken: "Your Discord Token"
networks:
  discord-bot-tier: {}