"""Add server id to song requests

Revision ID: e51463fc1bb8
Revises: e0b36a055fb6
Create Date: 2024-03-10 14:36:49.825738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e51463fc1bb8"
down_revision: Union[str, None] = "e0b36a055fb6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("songrequest", sa.Column("server_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("songrequest", "server_id")
    # ### end Alembic commands ###
