cogs:
  music:
    online:
      ytdl_format_options:
        format: "bestaudio/best"
        outtmpl: "%(extractor)s-%(id)s-%(title)s.%(ext)s"
        restrictfilenames: True
        noplaylist: False
        nocheckcertificate: True
        ignoreerrors: False
        logtostderr: False
        quiet: True
        no_warnings: True
        audioformat: "mp3"
        default_search: "auto"
        source_address: "0.0.0.0"
      ffmpeg_options:
        before_options: "-reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5"
        options: "-vn"
      default_info:
        uploader: "Max Raabe & Palast Orchester"
        uploader_url: "https://www.youtube.com/channel/UCXh3cIvGrgFnYYDV4Bzru0Q"
        upload_date: "21.11.2019"
        title: "Mein kleiner grüner Kaktus (MTV Unplugged) "
        thumbnail: "https://www.silvaporto.com.br/wp-content/uploads/2017/08/default_thumbnail-768x576.jpg"
        description: "Beste"
        duration: 136
        url: "https://www.youtube.com/watch?v=LpEIfFuP3O4"
  deutschebahn:
    hour: 12